## Analyse Exploratoire

### Import des modules

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import warnings
warnings.filterwarnings("ignore")

### Vision globale des données Train et Test

#### Chargement des données brutes

In [2]:
app_test = pd.read_csv("./Donnees_Brutes/application_test.csv", sep=',')
app_train = pd.read_csv("./Donnees_Brutes/application_train.csv", sep=',')

#### Découverte des données train et test

In [3]:
# Vue globale des données
pd.set_option("display.max_info_columns", 200)
jeu_donnee = [app_train, app_test]
noms = ["Train", "Test"]
for nom, df in zip(noms, jeu_donnee):
    print(f"\n--- Résumé {nom} ---")
    display(df.head())

--- Résumé Train ---

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

--- Résumé Test ---

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Dimensions des données
for nom, df in zip(noms, jeu_donnee):
    print(f"\n--- Résumé {nom} ---")
    display(df.shape)

--- Résumé Train ---

(307511, 122)

--- Résumé Test ---

(48744, 121)

In [5]:
# Résumé types de données
pd.set_option("display.max_info_columns", 200)
for nom, df in zip(noms, jeu_donnee):
    print(f"\n--- Informations sur {nom} ---")
    display(df.info())

--- Informations sur Train ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 122 columns):
 #    Column                        Non-Null Count   Dtype
---   ------                        --------------   -----
 0    SK_ID_CURR                    307511 non-null  int64
 1    TARGET                        307511 non-null  int64
 2    NAME_CONTRACT_TYPE            307511 non-null  object
 3    CODE_GENDER                   307511 non-null  object
 4    FLAG_OWN_CAR                  307511 non-null  object
 5    FLAG_OWN_REALTY               307511 non-null  object
 6    CNT_CHILDREN                  307511 non-null  int64
 7    AMT_INCOME_TOTAL              307511 non-null  float64
 8    AMT_CREDIT                    307511 non-null  float64
 9    AMT_ANNUITY                   307499 non-null  float64
 10   AMT_GOODS_PRICE               307233 non-null  float64
 11   NAME_TYPE_SUITE               306219 non-null  object
 12   NAME_INCOME_TYPE              307511 non-null  object
 13   NAME_EDUCATION_TYPE           307511 non-null  object
 14   NAME_FAMILY_STATUS            307511 non-null  object
 15   NAME_HOUSING_TYPE             307511 non-null  object
 16   REGION_POPULATION_RELATIVE    307511 non-null  float64
 17   DAYS_BIRTH                    307511 non-null  int64
 18   DAYS_EMPLOYED                 307511 non-null  int64
 19   DAYS_REGISTRATION             307511 non-null  float64
 20   DAYS_ID_PUBLISH               307511 non-null  int64
 21   OWN_CAR_AGE                   104582 non-null  float64
 22   FLAG_MOBIL                    307511 non-null  int64
 23   FLAG_EMP_PHONE                307511 non-null  int64
 24   FLAG_WORK_PHONE               307511 non-null  int64
 25   FLAG_CONT_MOBILE              307511 non-null  int64
 26   FLAG_PHONE                    307511 non-null  int64
 27   FLAG_EMAIL                    307511 non-null  int64
 28   OCCUPATION_TYPE               211120 non-null  object
 29   CNT_FAM_MEMBERS               307509 non-null  float64
 30   REGION_RATING_CLIENT          307511 non-null  int64
 31   REGION_RATING_CLIENT_W_CITY   307511 non-null  int64
 32   WEEKDAY_APPR_PROCESS_START    307511 non-null  object
 33   HOUR_APPR_PROCESS_START       307511 non-null  int64
 34   REG_REGION_NOT_LIVE_REGION    307511 non-null  int64
 35   REG_REGION_NOT_WORK_REGION    307511 non-null  int64
 36   LIVE_REGION_NOT_WORK_REGION   307511 non-null  int64
 37   REG_CITY_NOT_LIVE_CITY        307511 non-null  int64
 38   REG_CITY_NOT_WORK_CITY        307511 non-null  int64
 39   LIVE_CITY_NOT_WORK_CITY       307511 non-null  int64
 40   ORGANIZATION_TYPE             307511 non-null  object
 41   EXT_SOURCE_1                  134133 non-null  float64
 42   EXT_SOURCE_2                  306851 non-null  float64
 43   EXT_SOURCE_3                  246546 non-null  float64
 44   APARTMENTS_AVG                151450 non-null  float64
 45   BASEMENTAREA_AVG              127568 non-null  float64
 46   YEARS_BEGINEXPLUATATION_AVG   157504 non-null  float64
 47   YEARS_BUILD_AVG               103023 non-null  float64
 48   COMMONAREA_AVG                92646 non-null   float64
 49   ELEVATORS_AVG                 143620 non-null  float64
 50   ENTRANCES_AVG                 152683 non-null  float64
 51   FLOORSMAX_AVG                 154491 non-null  float64
 52   FLOORSMIN_AVG                 98869 non-null   float64
 53   LANDAREA_AVG                  124921 non-null  float64
 54   LIVINGAPARTMENTS_AVG          97312 non-null   float64
 55   LIVINGAREA_AVG                153161 non-null  float64
 56   NONLIVINGAPARTMENTS_AVG       93997 non-null   float64
 57   NONLIVINGAREA_AVG             137829 non-null  float64
 58   APARTMENTS_MODE               151450 non-null  float64
 59   BASEMENTAREA_MODE             127568 non-null  float64
 60   YEARS_BEGINEXPLUATATION_MODE  157504 non-null  float64
 61   YEARS_BUILD_MODE              103023 non-null  float64
 62   COMMONAREA_MODE               92646 non-null   float64
 63   ELEVATORS_MODE                143620 non-null  float64
 64   ENTRANCES_MODE                152683 non-null  float64
 65   FLOORSMAX_MODE                154491 non-null  float64
 66   FLOORSMIN_MODE                98869 non-null   float64
 67   LANDAREA_MODE                 124921 non-null  float64
 68   LIVINGAPARTMENTS_MODE         97312 non-null   float64
 69   LIVINGAREA_MODE               153161 non-null  float64
 70   NONLIVINGAPARTMENTS_MODE      93997 non-null   float64
 71   NONLIVINGAREA_MODE            137829 non-null  float64
 72   APARTMENTS_MEDI               151450 non-null  float64
 73   BASEMENTAREA_MEDI             127568 non-null  float64
 74   YEARS_BEGINEXPLUATATION_MEDI  157504 non-null  float64
 75   YEARS_BUILD_MEDI              103023 non-null  float64
 76   COMMONAREA_MEDI               92646 non-null   float64
 77   ELEVATORS_MEDI                143620 non-null  float64
 78   ENTRANCES_MEDI                152683 non-null  float64
 79   FLOORSMAX_MEDI                154491 non-null  float64
 80   FLOORSMIN_MEDI                98869 non-null   float64
 81   LANDAREA_MEDI                 124921 non-null  float64
 82   LIVINGAPARTMENTS_MEDI         97312 non-null   float64
 83   LIVINGAREA_MEDI               153161 non-null  float64
 84   NONLIVINGAPARTMENTS_MEDI      93997 non-null   float64
 85   NONLIVINGAREA_MEDI            137829 non-null  float64
 86   FONDKAPREMONT_MODE            97216 non-null   object
 87   HOUSETYPE_MODE                153214 non-null  object
 88   TOTALAREA_MODE                159080 non-null  float64
 89   WALLSMATERIAL_MODE            151170 non-null  object
 90   EMERGENCYSTATE_MODE           161756 non-null  object
 91   OBS_30_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 92   DEF_30_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 93   OBS_60_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 94   DEF_60_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 95   DAYS_LAST_PHONE_CHANGE        307510 non-null  float64
 96   FLAG_DOCUMENT_2               307511 non-null  int64
 97   FLAG_DOCUMENT_3               307511 non-null  int64
 98   FLAG_DOCUMENT_4               307511 non-null  int64
 99   FLAG_DOCUMENT_5               307511 non-null  int64
 100  FLAG_DOCUMENT_6               307511 non-null  int64
 101  FLAG_DOCUMENT_7               307511 non-null  int64
 102  FLAG_DOCUMENT_8               307511 non-null  int64
 103  FLAG_DOCUMENT_9               307511 non-null  int64
 104  FLAG_DOCUMENT_10              307511 non-null  int64
 105  FLAG_DOCUMENT_11              307511 non-null  int64
 106  FLAG_DOCUMENT_12              307511 non-null  int64
 107  FLAG_DOCUMENT_13              307511 non-null  int64
 108  FLAG_DOCUMENT_14              307511 non-null  int64
 109  FLAG_DOCUMENT_15              307511 non-null  int64
 110  FLAG_DOCUMENT_16              307511 non-null  int64
 111  FLAG_DOCUMENT_17              307511 non-null  int64
 112  FLAG_DOCUMENT_18              307511 non-null  int64
 113  FLAG_DOCUMENT_19              307511 non-null  int64
 114  FLAG_DOCUMENT_20              307511 non-null  int64
 115  FLAG_DOCUMENT_21              307511 non-null  int64
 116  AMT_REQ_CREDIT_BUREAU_HOUR    265992 non-null  float64
 117  AMT_REQ_CREDIT_BUREAU_DAY     265992 non-null  float64
 118  AMT_REQ_CREDIT_BUREAU_WEEK    265992 non-null  float64
 119  AMT_REQ_CREDIT_BUREAU_MON     265992 non-null  float64
 120  AMT_REQ_CREDIT_BUREAU_QRT     265992 non-null  float64
 121  AMT_REQ_CREDIT_BUREAU_YEAR    265992 non-null  float64
dtypes: float64(65), int64(41), object(16)
memory usage: 286.2+ MB

None

--- Informations sur Test ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48744 entries, 0 to 48743
Data columns (total 121 columns):
 #    Column                        Non-Null Count  Dtype
---   ------                        --------------  -----
 0    SK_ID_CURR                    48744 non-null  int64
 1    NAME_CONTRACT_TYPE            48744 non-null  object
 2    CODE_GENDER                   48744 non-null  object
 3    FLAG_OWN_CAR                  48744 non-null  object
 4    FLAG_OWN_REALTY               48744 non-null  object
 5    CNT_CHILDREN                  48744 non-null  int64
 6    AMT_INCOME_TOTAL              48744 non-null  float64
 7    AMT_CREDIT                    48744 non-null  float64
 8    AMT_ANNUITY                   48720 non-null  float64
 9    AMT_GOODS_PRICE               48744 non-null  float64
 10   NAME_TYPE_SUITE               47833 non-null  object
 11   NAME_INCOME_TYPE              48744 non-null  object
 12   NAME_EDUCATION_TYPE           48744 non-null  object
 13   NAME_FAMILY_STATUS            48744 non-null  object
 14   NAME_HOUSING_TYPE             48744 non-null  object
 15   REGION_POPULATION_RELATIVE    48744 non-null  float64
 16   DAYS_BIRTH                    48744 non-null  int64
 17   DAYS_EMPLOYED                 48744 non-null  int64
 18   DAYS_REGISTRATION             48744 non-null  float64
 19   DAYS_ID_PUBLISH               48744 non-null  int64
 20   OWN_CAR_AGE                   16432 non-null  float64
 21   FLAG_MOBIL                    48744 non-null  int64
 22   FLAG_EMP_PHONE                48744 non-null  int64
 23   FLAG_WORK_PHONE               48744 non-null  int64
 24   FLAG_CONT_MOBILE              48744 non-null  int64
 25   FLAG_PHONE                    48744 non-null  int64
 26   FLAG_EMAIL                    48744 non-null  int64
 27   OCCUPATION_TYPE               33139 non-null  object
 28   CNT_FAM_MEMBERS               48744 non-null  float64
 29   REGION_RATING_CLIENT          48744 non-null  int64
 30   REGION_RATING_CLIENT_W_CITY   48744 non-null  int64
 31   WEEKDAY_APPR_PROCESS_START    48744 non-null  object
 32   HOUR_APPR_PROCESS_START       48744 non-null  int64
 33   REG_REGION_NOT_LIVE_REGION    48744 non-null  int64
 34   REG_REGION_NOT_WORK_REGION    48744 non-null  int64
 35   LIVE_REGION_NOT_WORK_REGION   48744 non-null  int64
 36   REG_CITY_NOT_LIVE_CITY        48744 non-null  int64
 37   REG_CITY_NOT_WORK_CITY        48744 non-null  int64
 38   LIVE_CITY_NOT_WORK_CITY       48744 non-null  int64
 39   ORGANIZATION_TYPE             48744 non-null  object
 40   EXT_SOURCE_1                  28212 non-null  float64
 41   EXT_SOURCE_2                  48736 non-null  float64
 42   EXT_SOURCE_3                  40076 non-null  float64
 43   APARTMENTS_AVG                24857 non-null  float64
 44   BASEMENTAREA_AVG              21103 non-null  float64
 45   YEARS_BEGINEXPLUATATION_AVG   25888 non-null  float64
 46   YEARS_BUILD_AVG               16926 non-null  float64
 47   COMMONAREA_AVG                15249 non-null  float64
 48   ELEVATORS_AVG                 23555 non-null  float64
 49   ENTRANCES_AVG                 25165 non-null  float64
 50   FLOORSMAX_AVG                 25423 non-null  float64
 51   FLOORSMIN_AVG                 16278 non-null  float64
 52   LANDAREA_AVG                  20490 non-null  float64
 53   LIVINGAPARTMENTS_AVG          15964 non-null  float64
 54   LIVINGAREA_AVG                25192 non-null  float64
 55   NONLIVINGAPARTMENTS_AVG       15397 non-null  float64
 56   NONLIVINGAREA_AVG             22660 non-null  float64
 57   APARTMENTS_MODE               24857 non-null  float64
 58   BASEMENTAREA_MODE             21103 non-null  float64
 59   YEARS_BEGINEXPLUATATION_MODE  25888 non-null  float64
 60   YEARS_BUILD_MODE              16926 non-null  float64
 61   COMMONAREA_MODE               15249 non-null  float64
 62   ELEVATORS_MODE                23555 non-null  float64
 63   ENTRANCES_MODE                25165 non-null  float64
 64   FLOORSMAX_MODE                25423 non-null  float64
 65   FLOORSMIN_MODE                16278 non-null  float64
 66   LANDAREA_MODE                 20490 non-null  float64
 67   LIVINGAPARTMENTS_MODE         15964 non-null  float64
 68   LIVINGAREA_MODE               25192 non-null  float64
 69   NONLIVINGAPARTMENTS_MODE      15397 non-null  float64
 70   NONLIVINGAREA_MODE            22660 non-null  float64
 71   APARTMENTS_MEDI               24857 non-null  float64
 72   BASEMENTAREA_MEDI             21103 non-null  float64
 73   YEARS_BEGINEXPLUATATION_MEDI  25888 non-null  float64
 74   YEARS_BUILD_MEDI              16926 non-null  float64
 75   COMMONAREA_MEDI               15249 non-null  float64
 76   ELEVATORS_MEDI                23555 non-null  float64
 77   ENTRANCES_MEDI                25165 non-null  float64
 78   FLOORSMAX_MEDI                25423 non-null  float64
 79   FLOORSMIN_MEDI                16278 non-null  float64
 80   LANDAREA_MEDI                 20490 non-null  float64
 81   LIVINGAPARTMENTS_MEDI         15964 non-null  float64
 82   LIVINGAREA_MEDI               25192 non-null  float64
 83   NONLIVINGAPARTMENTS_MEDI      15397 non-null  float64
 84   NONLIVINGAREA_MEDI            22660 non-null  float64
 85   FONDKAPREMONT_MODE            15947 non-null  object
 86   HOUSETYPE_MODE                25125 non-null  object
 87   TOTALAREA_MODE                26120 non-null  float64
 88   WALLSMATERIAL_MODE            24851 non-null  object
 89   EMERGENCYSTATE_MODE           26535 non-null  object
 90   OBS_30_CNT_SOCIAL_CIRCLE      48715 non-null  float64
 91   DEF_30_CNT_SOCIAL_CIRCLE      48715 non-null  float64
 92   OBS_60_CNT_SOCIAL_CIRCLE      48715 non-null  float64
 93   DEF_60_CNT_SOCIAL_CIRCLE      48715 non-null  float64
 94   DAYS_LAST_PHONE_CHANGE        48744 non-null  float64
 95   FLAG_DOCUMENT_2               48744 non-null  int64
 96   FLAG_DOCUMENT_3               48744 non-null  int64
 97   FLAG_DOCUMENT_4               48744 non-null  int64
 98   FLAG_DOCUMENT_5               48744 non-null  int64
 99   FLAG_DOCUMENT_6               48744 non-null  int64
 100  FLAG_DOCUMENT_7               48744 non-null  int64
 101  FLAG_DOCUMENT_8               48744 non-null  int64
 102  FLAG_DOCUMENT_9               48744 non-null  int64
 103  FLAG_DOCUMENT_10              48744 non-null  int64
 104  FLAG_DOCUMENT_11              48744 non-null  int64
 105  FLAG_DOCUMENT_12              48744 non-null  int64
 106  FLAG_DOCUMENT_13              48744 non-null  int64
 107  FLAG_DOCUMENT_14              48744 non-null  int64
 108  FLAG_DOCUMENT_15              48744 non-null  int64
 109  FLAG_DOCUMENT_16              48744 non-null  int64
 110  FLAG_DOCUMENT_17              48744 non-null  int64
 111  FLAG_DOCUMENT_18              48744 non-null  int64
 112  FLAG_DOCUMENT_19              48744 non-null  int64
 113  FLAG_DOCUMENT_20              48744 non-null  int64
 114  FLAG_DOCUMENT_21              48744 non-null  int64
 115  AMT_REQ_CREDIT_BUREAU_HOUR    42695 non-null  float64
 116  AMT_REQ_CREDIT_BUREAU_DAY     42695 non-null  float64
 117  AMT_REQ_CREDIT_BUREAU_WEEK    42695 non-null  float64
 118  AMT_REQ_CREDIT_BUREAU_MON     42695 non-null  float64
 119  AMT_REQ_CREDIT_BUREAU_QRT     42695 non-null  float64
 120  AMT_REQ_CREDIT_BUREAU_YEAR    42695 non-null  float64
dtypes: float64(65), int64(40), object(16)
memory usage: 45.0+ MB

None

In [6]:
# Vérification de doublons
for i, df in enumerate(jeu_donnee, start=0):
    print(f"DataFrame {i} - {df.duplicated().sum()}")

DataFrame 0 - 0
DataFrame 1 - 0

In [7]:
# Statistiques descriptives (transposées pour une meilleure lecture)
for nom, df in zip(noms, jeu_donnee):
    print(f"\n--- Statistiques descriptives - {nom} ---")
    display(df.describe().T)

--- Statistiques descriptives - Train ---

,count,mean,std,min,25%,50%,75%,max
SK_ID_CURR,307511.0,278180.518577,102790.175348,100002.0,189145.5,278202.0,367142.5,456255.0
TARGET,307511.0,0.080729,0.272419,0.0,0.0,0.0,0.0,1.0
CNT_CHILDREN,307511.0,0.417052,0.722121,0.0,0.0,0.0,1.0,19.0
AMT_INCOME_TOTAL,307511.0,168797.919297,237123.146279,25650.0,112500.0,147150.0,202500.0,117000000.0
AMT_CREDIT,307511.0,599025.999706,402490.776996,45000.0,270000.0,513531.0,808650.0,4050000.0
...,...,...,...,...,...,...,...,...
AMT_REQ_CREDIT_BUREAU_DAY,265992.0,0.007000,0.110757,0.0,0.0,0.0,0.0,9.0
AMT_REQ_CREDIT_BUREAU_WEEK,265992.0,0.034362,0.204685,0.0,0.0,0.0,0.0,8.0
AMT_REQ_CREDIT_BUREAU_MON,265992.0,0.267395,0.916002,0.0,0.0,0.0,0.0,27.0
AMT_REQ_CREDIT_BUREAU_QRT,265992.0,0.265474,0.794056,0.0,0.0,0.0,0.0,261.0
AMT_REQ_CREDIT_BUREAU_YEAR,265992.0,1.899974,1.869295,0.0,0.0,1.0,3.0,25.0

--- Statistiques descriptives - Test ---

,count,mean,std,min,25%,50%,75%,max
SK_ID_CURR,48744.0,277796.676350,103169.547296,100001.0,188557.75,277549.0,367555.5,456250.0
CNT_CHILDREN,48744.0,0.397054,0.709047,0.0,0.00,0.0,1.0,20.0
AMT_INCOME_TOTAL,48744.0,178431.805855,101522.591536,26941.5,112500.00,157500.0,225000.0,4410000.0
AMT_CREDIT,48744.0,516740.435561,365397.004174,45000.0,260640.00,450000.0,675000.0,2245500.0
AMT_ANNUITY,48720.0,29426.240209,16016.368315,2295.0,17973.00,26199.0,37390.5,180576.0
...,...,...,...,...,...,...,...,...
AMT_REQ_CREDIT_BUREAU_DAY,42695.0,0.001803,0.046132,0.0,0.00,0.0,0.0,2.0
AMT_REQ_CREDIT_BUREAU_WEEK,42695.0,0.002787,0.054037,0.0,0.00,0.0,0.0,2.0
AMT_REQ_CREDIT_BUREAU_MON,42695.0,0.009299,0.110924,0.0,0.00,0.0,0.0,6.0
AMT_REQ_CREDIT_BUREAU_QRT,42695.0,0.546902,0.693305,0.0,0.00,0.0,1.0,7.0
AMT_REQ_CREDIT_BUREAU_YEAR,42695.0,1.983769,1.838873,0.0,0.00,2.0,3.0,17.0

In [8]:
# Nombre de valeurs manquantes par colonne - ratio en %
pd.set_option("display.max_rows", None)
for nom, df in zip(noms, jeu_donnee):
    print(f"\n--- Valeurs manquantes BD {nom} ---")
    missing_values = df.isna().sum().reset_index()
    missing_values.columns = ["colonne", "valeurs_manquantes"]
    
    missing_values["pourcentage"] = (missing_values["valeurs_manquantes"] / df.shape[0] * 100).round(1)

    missing_values = missing_values[missing_values["valeurs_manquantes"] > 0]
    missing_values.sort_values("valeurs_manquantes", ascending=False, inplace=True)                                
    display(missing_values)

--- Valeurs manquantes BD Train ---

                          colonne  valeurs_manquantes  pourcentage
76                COMMONAREA_MEDI              214865         69.9
48                 COMMONAREA_AVG              214865         69.9
62                COMMONAREA_MODE              214865         69.9
84       NONLIVINGAPARTMENTS_MEDI              213514         69.4
70       NONLIVINGAPARTMENTS_MODE              213514         69.4
56        NONLIVINGAPARTMENTS_AVG              213514         69.4
86             FONDKAPREMONT_MODE              210295         68.4
68          LIVINGAPARTMENTS_MODE              210199         68.4
82          LIVINGAPARTMENTS_MEDI              210199         68.4
54           LIVINGAPARTMENTS_AVG              210199         68.4
66                 FLOORSMIN_MODE              208642         67.8
80                 FLOORSMIN_MEDI              208642         67.8
52                  FLOORSMIN_AVG              208642         67.8
61               YEARS_BUILD_MODE              204488         66.5
75               YEARS_BUILD_MEDI              204488         66.5
47                YEARS_BUILD_AVG              204488         66.5
21                    OWN_CAR_AGE              202929         66.0
53                   LANDAREA_AVG              182590         59.4
81                  LANDAREA_MEDI              182590         59.4
67                  LANDAREA_MODE              182590         59.4
73              BASEMENTAREA_MEDI              179943         58.5
45               BASEMENTAREA_AVG              179943         58.5
59              BASEMENTAREA_MODE              179943         58.5
41                   EXT_SOURCE_1              173378         56.4
85             NONLIVINGAREA_MEDI              169682         55.2
71             NONLIVINGAREA_MODE              169682         55.2
57              NONLIVINGAREA_AVG              169682         55.2
77                 ELEVATORS_MEDI              163891         53.3
63                 ELEVATORS_MODE              163891         53.3
49                  ELEVATORS_AVG              163891         53.3
89             WALLSMATERIAL_MODE              156341         50.8
58                APARTMENTS_MODE              156061         50.7
72                APARTMENTS_MEDI              156061         50.7
44                 APARTMENTS_AVG              156061         50.7
64                 ENTRANCES_MODE              154828         50.3
50                  ENTRANCES_AVG              154828         50.3
78                 ENTRANCES_MEDI              154828         50.3
83                LIVINGAREA_MEDI              154350         50.2
69                LIVINGAREA_MODE              154350         50.2
55                 LIVINGAREA_AVG              154350         50.2
87                 HOUSETYPE_MODE              154297         50.2
79                 FLOORSMAX_MEDI              153020         49.8
51                  FLOORSMAX_AVG              153020         49.8
65                 FLOORSMAX_MODE              153020         49.8
46    YEARS_BEGINEXPLUATATION_AVG              150007         48.8
74   YEARS_BEGINEXPLUATATION_MEDI              150007         48.8
60   YEARS_BEGINEXPLUATATION_MODE              150007         48.8
88                 TOTALAREA_MODE              148431         48.3
90            EMERGENCYSTATE_MODE              145755         47.4
28                OCCUPATION_TYPE               96391         31.3
43                   EXT_SOURCE_3               60965         19.8
118    AMT_REQ_CREDIT_BUREAU_WEEK               41519         13.5
117     AMT_REQ_CREDIT_BUREAU_DAY               41519         13.5
119     AMT_REQ_CREDIT_BUREAU_MON               41519         13.5
120     AMT_REQ_CREDIT_BUREAU_QRT               41519         13.5
116    AMT_REQ_CREDIT_BUREAU_HOUR               41519         13.5
121    AMT_REQ_CREDIT_BUREAU_YEAR               41519         13.5
11                NAME_TYPE_SUITE                1292          0.4
92       DEF_30_CNT_SOCIAL_CIRCLE                1021          0.3
93       OBS_60_CNT_SOCIAL_CIRCLE                1021          0.3
94       DEF_60_CNT_SOCIAL_CIRCLE                1021          0.3
91       OBS_30_CNT_SOCIAL_CIRCLE                1021          0.3
42                   EXT_SOURCE_2                 660          0.2
10                AMT_GOODS_PRICE                 278          0.1
9                     AMT_ANNUITY                  12          0.0
29                CNT_FAM_MEMBERS                   2          0.0
95         DAYS_LAST_PHONE_CHANGE                   1          0.0

--- Valeurs manquantes BD Test ---

                          colonne  valeurs_manquantes  pourcentage
61                COMMONAREA_MODE               33495         68.7
75                COMMONAREA_MEDI               33495         68.7
47                 COMMONAREA_AVG               33495         68.7
83       NONLIVINGAPARTMENTS_MEDI               33347         68.4
55        NONLIVINGAPARTMENTS_AVG               33347         68.4
69       NONLIVINGAPARTMENTS_MODE               33347         68.4
85             FONDKAPREMONT_MODE               32797         67.3
67          LIVINGAPARTMENTS_MODE               32780         67.2
81          LIVINGAPARTMENTS_MEDI               32780         67.2
53           LIVINGAPARTMENTS_AVG               32780         67.2
79                 FLOORSMIN_MEDI               32466         66.6
65                 FLOORSMIN_MODE               32466         66.6
51                  FLOORSMIN_AVG               32466         66.6
20                    OWN_CAR_AGE               32312         66.3
46                YEARS_BUILD_AVG               31818         65.3
74               YEARS_BUILD_MEDI               31818         65.3
60               YEARS_BUILD_MODE               31818         65.3
66                  LANDAREA_MODE               28254         58.0
52                   LANDAREA_AVG               28254         58.0
80                  LANDAREA_MEDI               28254         58.0
72              BASEMENTAREA_MEDI               27641         56.7
44               BASEMENTAREA_AVG               27641         56.7
58              BASEMENTAREA_MODE               27641         56.7
84             NONLIVINGAREA_MEDI               26084         53.5
70             NONLIVINGAREA_MODE               26084         53.5
56              NONLIVINGAREA_AVG               26084         53.5
76                 ELEVATORS_MEDI               25189         51.7
62                 ELEVATORS_MODE               25189         51.7
48                  ELEVATORS_AVG               25189         51.7
88             WALLSMATERIAL_MODE               23893         49.0
57                APARTMENTS_MODE               23887         49.0
71                APARTMENTS_MEDI               23887         49.0
43                 APARTMENTS_AVG               23887         49.0
86                 HOUSETYPE_MODE               23619         48.5
63                 ENTRANCES_MODE               23579         48.4
77                 ENTRANCES_MEDI               23579         48.4
49                  ENTRANCES_AVG               23579         48.4
54                 LIVINGAREA_AVG               23552         48.3
82                LIVINGAREA_MEDI               23552         48.3
68                LIVINGAREA_MODE               23552         48.3
78                 FLOORSMAX_MEDI               23321         47.8
64                 FLOORSMAX_MODE               23321         47.8
50                  FLOORSMAX_AVG               23321         47.8
73   YEARS_BEGINEXPLUATATION_MEDI               22856         46.9
59   YEARS_BEGINEXPLUATATION_MODE               22856         46.9
45    YEARS_BEGINEXPLUATATION_AVG               22856         46.9
87                 TOTALAREA_MODE               22624         46.4
89            EMERGENCYSTATE_MODE               22209         45.6
40                   EXT_SOURCE_1               20532         42.1
27                OCCUPATION_TYPE               15605         32.0
42                   EXT_SOURCE_3                8668         17.8
118     AMT_REQ_CREDIT_BUREAU_MON                6049         12.4
115    AMT_REQ_CREDIT_BUREAU_HOUR                6049         12.4
119     AMT_REQ_CREDIT_BUREAU_QRT                6049         12.4
117    AMT_REQ_CREDIT_BUREAU_WEEK                6049         12.4
116     AMT_REQ_CREDIT_BUREAU_DAY                6049         12.4
120    AMT_REQ_CREDIT_BUREAU_YEAR                6049         12.4
10                NAME_TYPE_SUITE                 911          1.9
93       DEF_60_CNT_SOCIAL_CIRCLE                  29          0.1
92       OBS_60_CNT_SOCIAL_CIRCLE                  29          0.1
91       DEF_30_CNT_SOCIAL_CIRCLE                  29          0.1
90       OBS_30_CNT_SOCIAL_CIRCLE                  29          0.1
8                     AMT_ANNUITY                  24          0.0
41                   EXT_SOURCE_2                   8          0.0

In [9]:
# Vérification des colonnes constantes
pd.set_option("display.max_rows", None)
for nom, df in zip(noms, jeu_donnee):
    print(f"\n--- Nombre de valeurs uniques - {nom} ---")
    constantes = df.nunique()
    constantes = constantes[constantes == 1]
    display(constantes)

--- Nombre de valeurs uniques - Train ---

Series([], dtype: int64)

--- Nombre de valeurs uniques - Test ---

FLAG_DOCUMENT_2     1
FLAG_DOCUMENT_10    1
FLAG_DOCUMENT_12    1
FLAG_DOCUMENT_13    1
FLAG_DOCUMENT_14    1
FLAG_DOCUMENT_15    1
FLAG_DOCUMENT_16    1
FLAG_DOCUMENT_17    1
FLAG_DOCUMENT_19    1
FLAG_DOCUMENT_20    1
FLAG_DOCUMENT_21    1
dtype: int64

In [10]:
# Modifier les formats des colonnes de type "bool" qui sont des int64 
def convertir_bool(df):
    df = df.copy()
    for col in df.select_dtypes(include=["int64", "float64"]).columns:
        valeurs_uniques = set(df[col].dropna().unique())
        if valeurs_uniques.issubset({0, 1}):
            df[col] = df[col].astype(bool)
    return df

app_train1 = convertir_bool(app_train)
app_test1 = convertir_bool(app_test)

In [11]:
pd.set_option("display.max_rows", None)

jeu_donnee = [app_train1, app_test1]
noms = ["Train", "Test"]
for nom, df in zip(noms, jeu_donnee):
    print(f"\n--- Valeurs manquantes BD {nom} ---")  

    display(df.info())

--- Valeurs manquantes BD Train ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 122 columns):
 #    Column                        Non-Null Count   Dtype
---   ------                        --------------   -----
 0    SK_ID_CURR                    307511 non-null  int64
 1    TARGET                        307511 non-null  bool
 2    NAME_CONTRACT_TYPE            307511 non-null  object
 3    CODE_GENDER                   307511 non-null  object
 4    FLAG_OWN_CAR                  307511 non-null  object
 5    FLAG_OWN_REALTY               307511 non-null  object
 6    CNT_CHILDREN                  307511 non-null  int64
 7    AMT_INCOME_TOTAL              307511 non-null  float64
 8    AMT_CREDIT                    307511 non-null  float64
 9    AMT_ANNUITY                   307499 non-null  float64
 10   AMT_GOODS_PRICE               307233 non-null  float64
 11   NAME_TYPE_SUITE               306219 non-null  object
 12   NAME_INCOME_TYPE              307511 non-null  object
 13   NAME_EDUCATION_TYPE           307511 non-null  object
 14   NAME_FAMILY_STATUS            307511 non-null  object
 15   NAME_HOUSING_TYPE             307511 non-null  object
 16   REGION_POPULATION_RELATIVE    307511 non-null  float64
 17   DAYS_BIRTH                    307511 non-null  int64
 18   DAYS_EMPLOYED                 307511 non-null  int64
 19   DAYS_REGISTRATION             307511 non-null  float64
 20   DAYS_ID_PUBLISH               307511 non-null  int64
 21   OWN_CAR_AGE                   104582 non-null  float64
 22   FLAG_MOBIL                    307511 non-null  bool
 23   FLAG_EMP_PHONE                307511 non-null  bool
 24   FLAG_WORK_PHONE               307511 non-null  bool
 25   FLAG_CONT_MOBILE              307511 non-null  bool
 26   FLAG_PHONE                    307511 non-null  bool
 27   FLAG_EMAIL                    307511 non-null  bool
 28   OCCUPATION_TYPE               211120 non-null  object
 29   CNT_FAM_MEMBERS               307509 non-null  float64
 30   REGION_RATING_CLIENT          307511 non-null  int64
 31   REGION_RATING_CLIENT_W_CITY   307511 non-null  int64
 32   WEEKDAY_APPR_PROCESS_START    307511 non-null  object
 33   HOUR_APPR_PROCESS_START       307511 non-null  int64
 34   REG_REGION_NOT_LIVE_REGION    307511 non-null  bool
 35   REG_REGION_NOT_WORK_REGION    307511 non-null  bool
 36   LIVE_REGION_NOT_WORK_REGION   307511 non-null  bool
 37   REG_CITY_NOT_LIVE_CITY        307511 non-null  bool
 38   REG_CITY_NOT_WORK_CITY        307511 non-null  bool
 39   LIVE_CITY_NOT_WORK_CITY       307511 non-null  bool
 40   ORGANIZATION_TYPE             307511 non-null  object
 41   EXT_SOURCE_1                  134133 non-null  float64
 42   EXT_SOURCE_2                  306851 non-null  float64
 43   EXT_SOURCE_3                  246546 non-null  float64
 44   APARTMENTS_AVG                151450 non-null  float64
 45   BASEMENTAREA_AVG              127568 non-null  float64
 46   YEARS_BEGINEXPLUATATION_AVG   157504 non-null  float64
 47   YEARS_BUILD_AVG               103023 non-null  float64
 48   COMMONAREA_AVG                92646 non-null   float64
 49   ELEVATORS_AVG                 143620 non-null  float64
 50   ENTRANCES_AVG                 152683 non-null  float64
 51   FLOORSMAX_AVG                 154491 non-null  float64
 52   FLOORSMIN_AVG                 98869 non-null   float64
 53   LANDAREA_AVG                  124921 non-null  float64
 54   LIVINGAPARTMENTS_AVG          97312 non-null   float64
 55   LIVINGAREA_AVG                153161 non-null  float64
 56   NONLIVINGAPARTMENTS_AVG       93997 non-null   float64
 57   NONLIVINGAREA_AVG             137829 non-null  float64
 58   APARTMENTS_MODE               151450 non-null  float64
 59   BASEMENTAREA_MODE             127568 non-null  float64
 60   YEARS_BEGINEXPLUATATION_MODE  157504 non-null  float64
 61   YEARS_BUILD_MODE              103023 non-null  float64
 62   COMMONAREA_MODE               92646 non-null   float64
 63   ELEVATORS_MODE                143620 non-null  float64
 64   ENTRANCES_MODE                152683 non-null  float64
 65   FLOORSMAX_MODE                154491 non-null  float64
 66   FLOORSMIN_MODE                98869 non-null   float64
 67   LANDAREA_MODE                 124921 non-null  float64
 68   LIVINGAPARTMENTS_MODE         97312 non-null   float64
 69   LIVINGAREA_MODE               153161 non-null  float64
 70   NONLIVINGAPARTMENTS_MODE      93997 non-null   float64
 71   NONLIVINGAREA_MODE            137829 non-null  float64
 72   APARTMENTS_MEDI               151450 non-null  float64
 73   BASEMENTAREA_MEDI             127568 non-null  float64
 74   YEARS_BEGINEXPLUATATION_MEDI  157504 non-null  float64
 75   YEARS_BUILD_MEDI              103023 non-null  float64
 76   COMMONAREA_MEDI               92646 non-null   float64
 77   ELEVATORS_MEDI                143620 non-null  float64
 78   ENTRANCES_MEDI                152683 non-null  float64
 79   FLOORSMAX_MEDI                154491 non-null  float64
 80   FLOORSMIN_MEDI                98869 non-null   float64
 81   LANDAREA_MEDI                 124921 non-null  float64
 82   LIVINGAPARTMENTS_MEDI         97312 non-null   float64
 83   LIVINGAREA_MEDI               153161 non-null  float64
 84   NONLIVINGAPARTMENTS_MEDI      93997 non-null   float64
 85   NONLIVINGAREA_MEDI            137829 non-null  float64
 86   FONDKAPREMONT_MODE            97216 non-null   object
 87   HOUSETYPE_MODE                153214 non-null  object
 88   TOTALAREA_MODE                159080 non-null  float64
 89   WALLSMATERIAL_MODE            151170 non-null  object
 90   EMERGENCYSTATE_MODE           161756 non-null  object
 91   OBS_30_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 92   DEF_30_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 93   OBS_60_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 94   DEF_60_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 95   DAYS_LAST_PHONE_CHANGE        307510 non-null  float64
 96   FLAG_DOCUMENT_2               307511 non-null  bool
 97   FLAG_DOCUMENT_3               307511 non-null  bool
 98   FLAG_DOCUMENT_4               307511 non-null  bool
 99   FLAG_DOCUMENT_5               307511 non-null  bool
 100  FLAG_DOCUMENT_6               307511 non-null  bool
 101  FLAG_DOCUMENT_7               307511 non-null  bool
 102  FLAG_DOCUMENT_8               307511 non-null  bool
 103  FLAG_DOCUMENT_9               307511 non-null  bool
 104  FLAG_DOCUMENT_10              307511 non-null  bool
 105  FLAG_DOCUMENT_11              307511 non-null  bool
 106  FLAG_DOCUMENT_12              307511 non-null  bool
 107  FLAG_DOCUMENT_13              307511 non-null  bool
 108  FLAG_DOCUMENT_14              307511 non-null  bool
 109  FLAG_DOCUMENT_15              307511 non-null  bool
 110  FLAG_DOCUMENT_16              307511 non-null  bool
 111  FLAG_DOCUMENT_17              307511 non-null  bool
 112  FLAG_DOCUMENT_18              307511 non-null  bool
 113  FLAG_DOCUMENT_19              307511 non-null  bool
 114  FLAG_DOCUMENT_20              307511 non-null  bool
 115  FLAG_DOCUMENT_21              307511 non-null  bool
 116  AMT_REQ_CREDIT_BUREAU_HOUR    265992 non-null  float64
 117  AMT_REQ_CREDIT_BUREAU_DAY     265992 non-null  float64
 118  AMT_REQ_CREDIT_BUREAU_WEEK    265992 non-null  float64
 119  AMT_REQ_CREDIT_BUREAU_MON     265992 non-null  float64
 120  AMT_REQ_CREDIT_BUREAU_QRT     265992 non-null  float64
 121  AMT_REQ_CREDIT_BUREAU_YEAR    265992 non-null  float64
dtypes: bool(33), float64(65), int64(8), object(16)
memory usage: 218.5+ MB

None

--- Valeurs manquantes BD Test ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48744 entries, 0 to 48743
Data columns (total 121 columns):
 #    Column                        Non-Null Count  Dtype
---   ------                        --------------  -----
 0    SK_ID_CURR                    48744 non-null  int64
 1    NAME_CONTRACT_TYPE            48744 non-null  object
 2    CODE_GENDER                   48744 non-null  object
 3    FLAG_OWN_CAR                  48744 non-null  object
 4    FLAG_OWN_REALTY               48744 non-null  object
 5    CNT_CHILDREN                  48744 non-null  int64
 6    AMT_INCOME_TOTAL              48744 non-null  float64
 7    AMT_CREDIT                    48744 non-null  float64
 8    AMT_ANNUITY                   48720 non-null  float64
 9    AMT_GOODS_PRICE               48744 non-null  float64
 10   NAME_TYPE_SUITE               47833 non-null  object
 11   NAME_INCOME_TYPE              48744 non-null  object
 12   NAME_EDUCATION_TYPE           48744 non-null  object
 13   NAME_FAMILY_STATUS            48744 non-null  object
 14   NAME_HOUSING_TYPE             48744 non-null  object
 15   REGION_POPULATION_RELATIVE    48744 non-null  float64
 16   DAYS_BIRTH                    48744 non-null  int64
 17   DAYS_EMPLOYED                 48744 non-null  int64
 18   DAYS_REGISTRATION             48744 non-null  float64
 19   DAYS_ID_PUBLISH               48744 non-null  int64
 20   OWN_CAR_AGE                   16432 non-null  float64
 21   FLAG_MOBIL                    48744 non-null  bool
 22   FLAG_EMP_PHONE                48744 non-null  bool
 23   FLAG_WORK_PHONE               48744 non-null  bool
 24   FLAG_CONT_MOBILE              48744 non-null  bool
 25   FLAG_PHONE                    48744 non-null  bool
 26   FLAG_EMAIL                    48744 non-null  bool
 27   OCCUPATION_TYPE               33139 non-null  object
 28   CNT_FAM_MEMBERS               48744 non-null  float64
 29   REGION_RATING_CLIENT          48744 non-null  int64
 30   REGION_RATING_CLIENT_W_CITY   48744 non-null  int64
 31   WEEKDAY_APPR_PROCESS_START    48744 non-null  object
 32   HOUR_APPR_PROCESS_START       48744 non-null  int64
 33   REG_REGION_NOT_LIVE_REGION    48744 non-null  bool
 34   REG_REGION_NOT_WORK_REGION    48744 non-null  bool
 35   LIVE_REGION_NOT_WORK_REGION   48744 non-null  bool
 36   REG_CITY_NOT_LIVE_CITY        48744 non-null  bool
 37   REG_CITY_NOT_WORK_CITY        48744 non-null  bool
 38   LIVE_CITY_NOT_WORK_CITY       48744 non-null  bool
 39   ORGANIZATION_TYPE             48744 non-null  object
 40   EXT_SOURCE_1                  28212 non-null  float64
 41   EXT_SOURCE_2                  48736 non-null  float64
 42   EXT_SOURCE_3                  40076 non-null  float64
 43   APARTMENTS_AVG                24857 non-null  float64
 44   BASEMENTAREA_AVG              21103 non-null  float64
 45   YEARS_BEGINEXPLUATATION_AVG   25888 non-null  float64
 46   YEARS_BUILD_AVG               16926 non-null  float64
 47   COMMONAREA_AVG                15249 non-null  float64
 48   ELEVATORS_AVG                 23555 non-null  float64
 49   ENTRANCES_AVG                 25165 non-null  float64
 50   FLOORSMAX_AVG                 25423 non-null  float64
 51   FLOORSMIN_AVG                 16278 non-null  float64
 52   LANDAREA_AVG                  20490 non-null  float64
 53   LIVINGAPARTMENTS_AVG          15964 non-null  float64
 54   LIVINGAREA_AVG                25192 non-null  float64
 55   NONLIVINGAPARTMENTS_AVG       15397 non-null  float64
 56   NONLIVINGAREA_AVG             22660 non-null  float64
 57   APARTMENTS_MODE               24857 non-null  float64
 58   BASEMENTAREA_MODE             21103 non-null  float64
 59   YEARS_BEGINEXPLUATATION_MODE  25888 non-null  float64
 60   YEARS_BUILD_MODE              16926 non-null  float64
 61   COMMONAREA_MODE               15249 non-null  float64
 62   ELEVATORS_MODE                23555 non-null  float64
 63   ENTRANCES_MODE                25165 non-null  float64
 64   FLOORSMAX_MODE                25423 non-null  float64
 65   FLOORSMIN_MODE                16278 non-null  float64
 66   LANDAREA_MODE                 20490 non-null  float64
 67   LIVINGAPARTMENTS_MODE         15964 non-null  float64
 68   LIVINGAREA_MODE               25192 non-null  float64
 69   NONLIVINGAPARTMENTS_MODE      15397 non-null  float64
 70   NONLIVINGAREA_MODE            22660 non-null  float64
 71   APARTMENTS_MEDI               24857 non-null  float64
 72   BASEMENTAREA_MEDI             21103 non-null  float64
 73   YEARS_BEGINEXPLUATATION_MEDI  25888 non-null  float64
 74   YEARS_BUILD_MEDI              16926 non-null  float64
 75   COMMONAREA_MEDI               15249 non-null  float64
 76   ELEVATORS_MEDI                23555 non-null  float64
 77   ENTRANCES_MEDI                25165 non-null  float64
 78   FLOORSMAX_MEDI                25423 non-null  float64
 79   FLOORSMIN_MEDI                16278 non-null  float64
 80   LANDAREA_MEDI                 20490 non-null  float64
 81   LIVINGAPARTMENTS_MEDI         15964 non-null  float64
 82   LIVINGAREA_MEDI               25192 non-null  float64
 83   NONLIVINGAPARTMENTS_MEDI      15397 non-null  float64
 84   NONLIVINGAREA_MEDI            22660 non-null  float64
 85   FONDKAPREMONT_MODE            15947 non-null  object
 86   HOUSETYPE_MODE                25125 non-null  object
 87   TOTALAREA_MODE                26120 non-null  float64
 88   WALLSMATERIAL_MODE            24851 non-null  object
 89   EMERGENCYSTATE_MODE           26535 non-null  object
 90   OBS_30_CNT_SOCIAL_CIRCLE      48715 non-null  float64
 91   DEF_30_CNT_SOCIAL_CIRCLE      48715 non-null  float64
 92   OBS_60_CNT_SOCIAL_CIRCLE      48715 non-null  float64
 93   DEF_60_CNT_SOCIAL_CIRCLE      48715 non-null  float64
 94   DAYS_LAST_PHONE_CHANGE        48744 non-null  float64
 95   FLAG_DOCUMENT_2               48744 non-null  bool
 96   FLAG_DOCUMENT_3               48744 non-null  bool
 97   FLAG_DOCUMENT_4               48744 non-null  bool
 98   FLAG_DOCUMENT_5               48744 non-null  bool
 99   FLAG_DOCUMENT_6               48744 non-null  bool
 100  FLAG_DOCUMENT_7               48744 non-null  bool
 101  FLAG_DOCUMENT_8               48744 non-null  bool
 102  FLAG_DOCUMENT_9               48744 non-null  bool
 103  FLAG_DOCUMENT_10              48744 non-null  bool
 104  FLAG_DOCUMENT_11              48744 non-null  bool
 105  FLAG_DOCUMENT_12              48744 non-null  bool
 106  FLAG_DOCUMENT_13              48744 non-null  bool
 107  FLAG_DOCUMENT_14              48744 non-null  bool
 108  FLAG_DOCUMENT_15              48744 non-null  bool
 109  FLAG_DOCUMENT_16              48744 non-null  bool
 110  FLAG_DOCUMENT_17              48744 non-null  bool
 111  FLAG_DOCUMENT_18              48744 non-null  bool
 112  FLAG_DOCUMENT_19              48744 non-null  bool
 113  FLAG_DOCUMENT_20              48744 non-null  bool
 114  FLAG_DOCUMENT_21              48744 non-null  bool
 115  AMT_REQ_CREDIT_BUREAU_HOUR    42695 non-null  float64
 116  AMT_REQ_CREDIT_BUREAU_DAY     42695 non-null  float64
 117  AMT_REQ_CREDIT_BUREAU_WEEK    42695 non-null  float64
 118  AMT_REQ_CREDIT_BUREAU_MON     42695 non-null  float64
 119  AMT_REQ_CREDIT_BUREAU_QRT     42695 non-null  float64
 120  AMT_REQ_CREDIT_BUREAU_YEAR    42695 non-null  float64
dtypes: bool(32), float64(65), int64(8), object(16)
memory usage: 34.6+ MB

None

In [12]:
# Distribution du montant moyen de crédit par cible
credit_par_target = (
    app_train1
    .groupby("TARGET")["AMT_CREDIT"]
    .agg(["count", "mean"])
)

credit_par_target

         count           mean
TARGET
False   282686  602648.282002
True     24825  557778.527674

In [13]:
# Distribution du prix moyen du produit lié au crédit par cible
genre_par_target = app_train1.groupby(["TARGET", "CODE_GENDER"]).size()
genre_par_target

TARGET  CODE_GENDER
False   F              188278
        M               94404
        XNA                 4
True    F               14170
        M               10655
dtype: int64

In [14]:
summary = (
    app_train1
    .assign(AGE = app_train1["DAYS_BIRTH"] / -365)
    .groupby("TARGET")
    .agg(
        nb_clients = ("SK_ID_CURR", "count"),
        credit_moyen = ("AMT_CREDIT", "mean"),
        prix_produit_moyen = ("AMT_GOODS_PRICE", "mean"),
        annuite_moyenne = ("AMT_ANNUITY", "mean"),
        age_moyen = ("AGE", "mean"),
        age_median = ("AGE", "median")
    )
    .reset_index()
)

summary

,TARGET,nb_clients,credit_moyen,prix_produit_moyen,annuite_moyenne,age_moyen,age_median
0,False,282686,602648.282002,542736.795003,27163.623349,44.214182,43.498630
1,True,24825,557778.527674,488972.412554,26481.744290,40.780351,39.128767

### Fusion des fichiers avec Train & Test

#### Fusion des fichiers bureau + bureau_balance avec "train/test"
- Fusionner bureau + bureau_balance
- aggréger les données obtenues afin de pouvoir les intégrer dans le train/test
- Fusionner avec train & test

In [15]:
# Charger les données bureau
bureau_balance = pd.read_csv("./Donnees_Brutes/bureau_balance.csv", sep=',')
bureau = pd.read_csv("./Donnees_Brutes/bureau.csv", sep=',')

In [16]:
# Fusion des fichiers bureau + bureau_balance
bureau_merged = pd.merge(bureau, bureau_balance, on='SK_ID_BUREAU', how='left')
bureau_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25121815 entries, 0 to 25121814
Data columns (total 19 columns):
 #   Column                  Dtype
---  ------                  -----
 0   SK_ID_CURR              int64
 1   SK_ID_BUREAU            int64
 2   CREDIT_ACTIVE           object
 3   CREDIT_CURRENCY         object
 4   DAYS_CREDIT             int64
 5   CREDIT_DAY_OVERDUE      int64
 6   DAYS_CREDIT_ENDDATE     float64
 7   DAYS_ENDDATE_FACT       float64
 8   AMT_CREDIT_MAX_OVERDUE  float64
 9   CNT_CREDIT_PROLONG      int64
 10  AMT_CREDIT_SUM          float64
 11  AMT_CREDIT_SUM_DEBT     float64
 12  AMT_CREDIT_SUM_LIMIT    float64
 13  AMT_CREDIT_SUM_OVERDUE  float64
 14  CREDIT_TYPE             object
 15  DAYS_CREDIT_UPDATE      int64
 16  AMT_ANNUITY             float64
 17  MONTHS_BALANCE          float64
 18  STATUS                  object
dtypes: float64(9), int64(6), object(4)
memory usage: 3.6+ GB

In [17]:
def check_columns(df_ref, df_test, name_ref="train", name_test="test"):
    cols_ref = set(df_ref.columns)
    cols_test = set(df_test.columns)

    missing = cols_ref - cols_test
    extra = cols_test - cols_ref

    print(f"--- Vérification colonnes : {name_test} vs {name_ref} ---")
    print(f"Colonnes attendues : {len(cols_ref)}")
    print(f"Colonnes trouvées  : {len(cols_test)}")

    if missing:
        print("\n❌ Colonnes manquantes dans", name_test, ":")
        for c in sorted(missing):
            print("   -", c)
    else:
        print("\n✔️ Aucune colonne manquante")

    if extra:
        print("\n⚠️ Colonnes supplémentaires dans", name_test, ":")
        for c in sorted(extra):
            print("   -", c)
    else:
        print("\n✔️ Aucune colonne supplémentaire")

    print("\n--------------------------------------------\n")

In [18]:
# Fonction d'aggrégation previous_app
def agg_fichiers(data, prefix="PREV"):

    df = data.copy()

    # Sélection des colonnes
    num_cols = df.select_dtypes(include=["int64", "float64"]).columns.tolist()
    cat_cols = df.select_dtypes(include=["object"]).columns.tolist()

    # Exclure les identifiants des numériques lorsqu'ils existent
    num_cols = [c for c in num_cols if c not in df.columns.intersection(["SK_ID_CURR", "SK_ID_PREV"])]


    # Agrégations numériques
    print("Début agg numériques")

    num_aggs = {col: ["mean", "max", "min", "sum"] for col in num_cols}

    num_agg = df.groupby("SK_ID_CURR").agg(num_aggs)
    num_agg.columns = [f"{prefix}_" + "_".join(col) for col in num_agg.columns]
    num_agg = num_agg.reset_index()

    print("Fin agg numériques")

    # Agrégations catégorielles : NUNIQUE
    print("Début nunique cat")

    if cat_cols:
        cat_nunique = (
            df.groupby("SK_ID_CURR")[cat_cols]
            .nunique()
            .reset_index()
        )
        cat_nunique.columns = ["SK_ID_CURR"] + [f"{prefix}_{c}_NUNIQUE" for c in cat_cols]
    else:
        cat_nunique = None

    print("Fin nunique cat")

    # Agrégations catégorielles
    print("Début dummies + groupby cat")

    cat_counts = None

    for i, col in enumerate(cat_cols, 1):
        print(f"Traitement {i}/{len(cat_cols)} : {col}")

        dummies = pd.get_dummies(df[col], prefix=f"{prefix}_{col}")
        dummies["SK_ID_CURR"] = df["SK_ID_CURR"]

        dummies_sum = dummies.groupby("SK_ID_CURR").sum().reset_index()

        if cat_counts is None:
            cat_counts = dummies_sum
        else:
            cat_counts = cat_counts.merge(dummies_sum, on="SK_ID_CURR", how="left")

    print("Fin catégoriel")

    # Fusion finale
    print("Fusion finale")

    df_agg = num_agg.copy()

    if cat_nunique is not None:
        df_agg = df_agg.merge(cat_nunique, on="SK_ID_CURR", how="left")

    if cat_counts is not None:
        df_agg = df_agg.merge(cat_counts, on="SK_ID_CURR", how="left")

    print("Agrégation terminée")
    return df_agg

In [19]:
bureau_merge_agg = agg_fichiers(data=bureau_merged, prefix="BUREAU")
bureau_merge_agg.head()

Début agg numériques
Fin agg numériques
Début nunique cat
Fin nunique cat
Début dummies + groupby cat
Traitement 1/4 : CREDIT_ACTIVE
Traitement 2/4 : CREDIT_CURRENCY
Traitement 3/4 : CREDIT_TYPE
Traitement 4/4 : STATUS
Fin catégoriel
Fusion finale
Agrégation terminée

,SK_ID_CURR,BUREAU_SK_ID_BUREAU_mean,BUREAU_SK_ID_BUREAU_max,BUREAU_SK_ID_BUREAU_min,BUREAU_SK_ID_BUREAU_sum,BUREAU_DAYS_CREDIT_mean,BUREAU_DAYS_CREDIT_max,BUREAU_DAYS_CREDIT_min,BUREAU_DAYS_CREDIT_sum,BUREAU_CREDIT_DAY_OVERDUE_mean,...,BUREAU_CREDIT_TYPE_Real estate loan,BUREAU_CREDIT_TYPE_Unknown type of loan,BUREAU_STATUS_0,BUREAU_STATUS_1,BUREAU_STATUS_2,BUREAU_STATUS_3,BUREAU_STATUS_4,BUREAU_STATUS_5,BUREAU_STATUS_C,BUREAU_STATUS_X
0,100001,5.896632e+06,5896636,5896630,1014220756,-1009.284884,-49,-1572,-173597,0.0,...,0,0,31,1,0,0,0,0,110,30
1,100002,6.152350e+06,6158909,6113835,676758452,-996.781818,-103,-1437,-109646,0.0,...,0,0,45,27,0,0,0,0,23,15
2,100003,5.885878e+06,5885880,5885877,23543514,-1400.750000,-606,-2586,-5603,0.0,...,0,0,0,0,0,0,0,0,0,0
3,100004,6.829134e+06,6829134,6829133,13658267,-867.000000,-408,-1326,-1734,0.0,...,0,0,0,0,0,0,0,0,0,0
4,100005,6.735201e+06,6735202,6735200,141439211,-272.380952,-62,-373,-5720,0.0,...,0,0,14,0,0,0,0,0,5,2

In [20]:
# Fusion train/test & bureau_merge_agg
app_train_clean1 = app_train1.merge(bureau_merge_agg, on="SK_ID_CURR", how="left")
app_test_clean1 = app_test1.merge(bureau_merge_agg, on="SK_ID_CURR", how="left")

print(app_train_clean1.shape, app_test_clean1.shape)

(307511, 213) (48744, 212)

In [22]:
# Check des colonnes entre train et test
check_columns(app_train_clean1, app_test_clean1, name_ref="train", name_test="test")

--- Vérification colonnes : test vs train ---
Colonnes attendues : 213
Colonnes trouvées  : 212

❌ Colonnes manquantes dans test :
   - TARGET

✔️ Aucune colonne supplémentaire

--------------------------------------------

#### Fusion previous_app avec "train/test"
- aggréger les données afin de pouvoir les intégrer dans le train/test
- Fusionner avec train & test

In [23]:
# Chargement des données sur les demandes précédentes
previous_app = pd.read_csv("./Donnees_Brutes/previous_application.csv", sep=',')
previous_app.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1670214 entries, 0 to 1670213
Data columns (total 37 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   SK_ID_PREV                   1670214 non-null  int64
 1   SK_ID_CURR                   1670214 non-null  int64
 2   NAME_CONTRACT_TYPE           1670214 non-null  object
 3   AMT_ANNUITY                  1297979 non-null  float64
 4   AMT_APPLICATION              1670214 non-null  float64
 5   AMT_CREDIT                   1670213 non-null  float64
 6   AMT_DOWN_PAYMENT             774370 non-null   float64
 7   AMT_GOODS_PRICE              1284699 non-null  float64
 8   WEEKDAY_APPR_PROCESS_START   1670214 non-null  object
 9   HOUR_APPR_PROCESS_START      1670214 non-null  int64
 10  FLAG_LAST_APPL_PER_CONTRACT  1670214 non-null  object
 11  NFLAG_LAST_APPL_IN_DAY       1670214 non-null  int64
 12  RATE_DOWN_PAYMENT            774370 non-null   float64
 13  RATE_INTEREST_PRIMARY        5951 non-null     float64
 14  RATE_INTEREST_PRIVILEGED     5951 non-null     float64
 15  NAME_CASH_LOAN_PURPOSE       1670214 non-null  object
 16  NAME_CONTRACT_STATUS         1670214 non-null  object
 17  DAYS_DECISION                1670214 non-null  int64
 18  NAME_PAYMENT_TYPE            1670214 non-null  object
 19  CODE_REJECT_REASON           1670214 non-null  object
 20  NAME_TYPE_SUITE              849809 non-null   object
 21  NAME_CLIENT_TYPE             1670214 non-null  object
 22  NAME_GOODS_CATEGORY          1670214 non-null  object
 23  NAME_PORTFOLIO               1670214 non-null  object
 24  NAME_PRODUCT_TYPE            1670214 non-null  object
 25  CHANNEL_TYPE                 1670214 non-null  object
 26  SELLERPLACE_AREA             1670214 non-null  int64
 27  NAME_SELLER_INDUSTRY         1670214 non-null  object
 28  CNT_PAYMENT                  1297984 non-null  float64
 29  NAME_YIELD_GROUP             1670214 non-null  object
 30  PRODUCT_COMBINATION          1669868 non-null  object
 31  DAYS_FIRST_DRAWING           997149 non-null   float64
 32  DAYS_FIRST_DUE               997149 non-null   float64
 33  DAYS_LAST_DUE_1ST_VERSION    997149 non-null   float64
 34  DAYS_LAST_DUE                997149 non-null   float64
 35  DAYS_TERMINATION             997149 non-null   float64
 36  NFLAG_INSURED_ON_APPROVAL    997149 non-null   float64
dtypes: float64(15), int64(6), object(16)
memory usage: 471.5+ MB

In [24]:
previous_app.head()

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
previous_app_agg = agg_fichiers(previous_app, prefix="PREV")
previous_app_agg.head()

Début agg numériques
Fin agg numériques
Début nunique cat
Fin nunique cat
Début dummies + groupby cat
Traitement 1/16 : NAME_CONTRACT_TYPE
Traitement 2/16 : WEEKDAY_APPR_PROCESS_START
Traitement 3/16 : FLAG_LAST_APPL_PER_CONTRACT
Traitement 4/16 : NAME_CASH_LOAN_PURPOSE
Traitement 5/16 : NAME_CONTRACT_STATUS
Traitement 6/16 : NAME_PAYMENT_TYPE
Traitement 7/16 : CODE_REJECT_REASON
Traitement 8/16 : NAME_TYPE_SUITE
Traitement 9/16 : NAME_CLIENT_TYPE
Traitement 10/16 : NAME_GOODS_CATEGORY
Traitement 11/16 : NAME_PORTFOLIO
Traitement 12/16 : NAME_PRODUCT_TYPE
Traitement 13/16 : CHANNEL_TYPE
Traitement 14/16 : NAME_SELLER_INDUSTRY
Traitement 15/16 : NAME_YIELD_GROUP
Traitement 16/16 : PRODUCT_COMBINATION
Fin catégoriel
Fusion finale
Agrégation terminée

,SK_ID_CURR,PREV_AMT_ANNUITY_mean,PREV_AMT_ANNUITY_max,PREV_AMT_ANNUITY_min,PREV_AMT_ANNUITY_sum,PREV_AMT_APPLICATION_mean,PREV_AMT_APPLICATION_max,PREV_AMT_APPLICATION_min,PREV_AMT_APPLICATION_sum,PREV_AMT_CREDIT_mean,...,PREV_PRODUCT_COMBINATION_Cash X-Sell: low,PREV_PRODUCT_COMBINATION_Cash X-Sell: middle,PREV_PRODUCT_COMBINATION_POS household with interest,PREV_PRODUCT_COMBINATION_POS household without interest,PREV_PRODUCT_COMBINATION_POS industry with interest,PREV_PRODUCT_COMBINATION_POS industry without interest,PREV_PRODUCT_COMBINATION_POS mobile with interest,PREV_PRODUCT_COMBINATION_POS mobile without interest,PREV_PRODUCT_COMBINATION_POS other with interest,PREV_PRODUCT_COMBINATION_POS others without interest
0,100001,3951.000,3951.000,3951.000,3951.000,24835.50,24835.5,24835.5,24835.5,23787.00,...,0,0,0,0,0,0,1,0,0,0
1,100002,9251.775,9251.775,9251.775,9251.775,179055.00,179055.0,179055.0,179055.0,179055.00,...,0,0,0,0,0,0,0,0,1,0
2,100003,56553.990,98356.995,6737.310,169661.970,435436.50,900000.0,68809.5,1306309.5,484191.00,...,1,0,1,0,1,0,0,0,0,0
3,100004,5357.250,5357.250,5357.250,5357.250,24282.00,24282.0,24282.0,24282.0,20106.00,...,0,0,0,0,0,0,0,1,0,0
4,100005,4813.200,4813.200,4813.200,4813.200,22308.75,44617.5,0.0,44617.5,20076.75,...,0,0,0,0,0,0,1,0,0,0

In [26]:
# Fusion avec train et test
app_train_clean2 = app_train_clean1.merge(previous_app_agg, on="SK_ID_CURR", how="left")
app_test_clean2 = app_test_clean1.merge(previous_app_agg, on="SK_ID_CURR", how="left")

print(app_train_clean2.shape, app_test_clean2.shape)

(307511, 448) (48744, 447)

In [31]:
# Check des colonnes entre train et test
check_columns(app_train_clean2, app_test_clean2, name_ref="train_prev", name_test="test_prev")

--- Vérification colonnes : test_prev vs train_prev ---
Colonnes attendues : 448
Colonnes trouvées  : 447

❌ Colonnes manquantes dans test_prev :
   - TARGET

✔️ Aucune colonne supplémentaire

--------------------------------------------

#### Fusion du fichier installments_payments avec "train/test"
Table mesurant le comportement de remboursement réel du client.
L'objectif c'est de pouvoir en obtenir:
- le retard de paiement: retard moyen/max, nombre de retards, % retards
- le comportement de paiement: montant total dû, mt total payé, % payé/dû, paiements partiels??, paiements en avance
- nm total d'échéances, nm de crédits différent, etc

Ainsi on va procéder, comme pour les fichiers précédents, à une aggrégation des données pour une meilleure intégration dans le train/test car un client peut avoir plusieurs paiements différents

In [28]:
installments_payments = pd.read_csv("./Donnees_Brutes/installments_payments.csv", sep=',')
installments_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13605401 entries, 0 to 13605400
Data columns (total 8 columns):
 #   Column                  Dtype
---  ------                  -----
 0   SK_ID_PREV              int64
 1   SK_ID_CURR              int64
 2   NUM_INSTALMENT_VERSION  float64
 3   NUM_INSTALMENT_NUMBER   int64
 4   DAYS_INSTALMENT         float64
 5   DAYS_ENTRY_PAYMENT      float64
 6   AMT_INSTALMENT          float64
 7   AMT_PAYMENT             float64
dtypes: float64(5), int64(3)
memory usage: 830.4 MB

In [29]:
# Ajout de variables qui pourraient être intéressantes

# Retard = date réelle - date prévue
installments_payments["PAYMENT_DELAY"] = installments_payments["DAYS_ENTRY_PAYMENT"] - installments_payments["DAYS_INSTALMENT"]

# Retard positif = paiement en retard
installments_payments["LATE_PAYMENT"] = (installments_payments["PAYMENT_DELAY"] > 0).astype(int)

# Paiement partiel
installments_payments["PARTIAL_PAYMENT"] = (installments_payments["AMT_PAYMENT"] < installments_payments["AMT_INSTALMENT"]).astype(int)

# Paiement en avance
installments_payments["EARLY_PAYMENT"] = (installments_payments["PAYMENT_DELAY"] < 0).astype(int)

# Ratio payé / dû
installments_payments["PAYMENT_RATIO"] = installments_payments["AMT_PAYMENT"] / installments_payments["AMT_INSTALMENT"]
installments_payments["PAYMENT_RATIO"].replace([np.inf, -np.inf], np.nan, inplace=True) # lorsque le ratio est une division avec "0", la donnée est remplacée par "NaN"

In [30]:
inst_payments_agg = agg_fichiers(installments_payments, prefix="INST_PAY")
inst_payments_agg.info()

Début agg numériques
Fin agg numériques
Début nunique cat
Fin nunique cat
Début dummies + groupby cat
Fin catégoriel
Fusion finale
Agrégation terminée
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339587 entries, 0 to 339586
Data columns (total 33 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SK_ID_CURR                            339587 non-null  int64
 1   INST_PAY_NUM_INSTALMENT_VERSION_mean  339587 non-null  float64
 2   INST_PAY_NUM_INSTALMENT_VERSION_max   339587 non-null  float64
 3   INST_PAY_NUM_INSTALMENT_VERSION_min   339587 non-null  float64
 4   INST_PAY_NUM_INSTALMENT_VERSION_sum   339587 non-null  float64
 5   INST_PAY_NUM_INSTALMENT_NUMBER_mean   339587 non-null  float64
 6   INST_PAY_NUM_INSTALMENT_NUMBER_max    339587 non-null  int64
 7   INST_PAY_NUM_INSTALMENT_NUMBER_min    339587 non-null  int64
 8   INST_PAY_NUM_INSTALMENT_NUMBER_sum    339587 non-null  int64
 9   INST_PAY_DAYS_INSTALMENT_mean         339587 non-null  float64
 10  INST_PAY_DAYS_INSTALMENT_max          339587 non-null  float64
 11  INST_PAY_DAYS_INSTALMENT_min          339587 non-null  float64
 12  INST_PAY_DAYS_INSTALMENT_sum          339587 non-null  float64
 13  INST_PAY_DAYS_ENTRY_PAYMENT_mean      339578 non-null  float64
 14  INST_PAY_DAYS_ENTRY_PAYMENT_max       339578 non-null  float64
 15  INST_PAY_DAYS_ENTRY_PAYMENT_min       339578 non-null  float64
 16  INST_PAY_DAYS_ENTRY_PAYMENT_sum       339587 non-null  float64
 17  INST_PAY_AMT_INSTALMENT_mean          339587 non-null  float64
 18  INST_PAY_AMT_INSTALMENT_max           339587 non-null  float64
 19  INST_PAY_AMT_INSTALMENT_min           339587 non-null  float64
 20  INST_PAY_AMT_INSTALMENT_sum           339587 non-null  float64
 21  INST_PAY_AMT_PAYMENT_mean             339578 non-null  float64
 22  INST_PAY_AMT_PAYMENT_max              339578 non-null  float64
 23  INST_PAY_AMT_PAYMENT_min              339578 non-null  float64
 24  INST_PAY_AMT_PAYMENT_sum              339587 non-null  float64
 25  INST_PAY_PAYMENT_DELAY_mean           339578 non-null  float64
 26  INST_PAY_PAYMENT_DELAY_max            339578 non-null  float64
 27  INST_PAY_PAYMENT_DELAY_min            339578 non-null  float64
 28  INST_PAY_PAYMENT_DELAY_sum            339587 non-null  float64
 29  INST_PAY_PAYMENT_RATIO_mean           339575 non-null  float64
 30  INST_PAY_PAYMENT_RATIO_max            339575 non-null  float64
 31  INST_PAY_PAYMENT_RATIO_min            339575 non-null  float64
 32  INST_PAY_PAYMENT_RATIO_sum            339587 non-null  float64
dtypes: float64(29), int64(4)
memory usage: 85.5 MB

In [33]:
# Fusion avec train/test
app_train_clean3 = app_train_clean2.merge(inst_payments_agg, on="SK_ID_CURR", how="left")
app_test_clean3  = app_test_clean2.merge(inst_payments_agg, on="SK_ID_CURR", how="left")

print(app_train_clean3.shape, app_test_clean3.shape)

(307511, 480) (48744, 479)

In [34]:
# Check des colonnes entre train et test
check_columns(app_train_clean3, app_test_clean3, name_ref="train_install", name_test="test_instal")

--- Vérification colonnes : test_instal vs train_install ---
Colonnes attendues : 480
Colonnes trouvées  : 479

❌ Colonnes manquantes dans test_instal :
   - TARGET

✔️ Aucune colonne supplémentaire

--------------------------------------------

#### Fusion de credit_card_balance & pos_cash_balance avec "train/test"

In [35]:
# Chargement des données credit card est cash balance
credit_card_balance = pd.read_csv("./Donnees_Brutes/credit_card_balance.csv", sep=',')
pos_cash_balance = pd.read_csv("./Donnees_Brutes/POS_CASH_balance.csv", sep=',')

In [36]:
# Vue globale des données
pd.set_option("display.max_info_columns", 200)
jeu_donnees = [credit_card_balance, pos_cash_balance]
noms_ = ["Credit card", "Cash balance"]
for nom, df in zip(noms_, jeu_donnees):
    print(f"\n--- Résumé {nom} ---")
    display(df.head(), df.info())

--- Résumé Credit card ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3840312 entries, 0 to 3840311
Data columns (total 23 columns):
 #   Column                      Dtype
---  ------                      -----
 0   SK_ID_PREV                  int64
 1   SK_ID_CURR                  int64
 2   MONTHS_BALANCE              int64
 3   AMT_BALANCE                 float64
 4   AMT_CREDIT_LIMIT_ACTUAL     int64
 5   AMT_DRAWINGS_ATM_CURRENT    float64
 6   AMT_DRAWINGS_CURRENT        float64
 7   AMT_DRAWINGS_OTHER_CURRENT  float64
 8   AMT_DRAWINGS_POS_CURRENT    float64
 9   AMT_INST_MIN_REGULARITY     float64
 10  AMT_PAYMENT_CURRENT         float64
 11  AMT_PAYMENT_TOTAL_CURRENT   float64
 12  AMT_RECEIVABLE_PRINCIPAL    float64
 13  AMT_RECIVABLE               float64
 14  AMT_TOTAL_RECEIVABLE        float64
 15  CNT_DRAWINGS_ATM_CURRENT    float64
 16  CNT_DRAWINGS_CURRENT        int64
 17  CNT_DRAWINGS_OTHER_CURRENT  float64
 18  CNT_DRAWINGS_POS_CURRENT    float64
 19  CNT_INSTALMENT_MATURE_CUM   float64
 20  NAME_CONTRACT_STATUS        object
 21  SK_DPD                      int64
 22  SK_DPD_DEF                  int64
dtypes: float64(15), int64(7), object(1)
memory usage: 673.9+ MB

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.970,135000,0.0,877.5,0.0,877.5,1700.325,...,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.0,0.0,0.0,2250.000,...,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.0,0.0,0.0,2250.000,...,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.0,0.0,0.0,11795.760,...,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.455,450000,0.0,11547.0,0.0,11547.0,22924.890,...,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0

None

--- Résumé Cash balance ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10001358 entries, 0 to 10001357
Data columns (total 8 columns):
 #   Column                 Dtype
---  ------                 -----
 0   SK_ID_PREV             int64
 1   SK_ID_CURR             int64
 2   MONTHS_BALANCE         int64
 3   CNT_INSTALMENT         float64
 4   CNT_INSTALMENT_FUTURE  float64
 5   NAME_CONTRACT_STATUS   object
 6   SK_DPD                 int64
 7   SK_DPD_DEF             int64
dtypes: float64(2), int64(5), object(1)
memory usage: 610.4+ MB

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,1803195,182943,-31,48.0,45.0,Active,0,0
1,1715348,367990,-33,36.0,35.0,Active,0,0
2,1784872,397406,-32,12.0,9.0,Active,0,0
3,1903291,269225,-35,48.0,42.0,Active,0,0
4,2341044,334279,-35,36.0,35.0,Active,0,0

None

In [37]:
# Ajout de colonnes dérivées dans la table credit_card
credit_card_balance["UTILIZATION"] = credit_card_balance["AMT_BALANCE"] / credit_card_balance["AMT_CREDIT_LIMIT_ACTUAL"]
credit_card_balance["UTILIZATION"].replace([np.inf, -np.inf], np.nan, inplace=True)

credit_card_balance["PAYMENT_RATIO"] = credit_card_balance["AMT_PAYMENT_TOTAL_CURRENT"] / credit_card_balance["AMT_DRAWINGS_CURRENT"]
credit_card_balance["PAYMENT_RATIO"].replace([np.inf, -np.inf], np.nan, inplace=True)

In [38]:
# Application de la fonction d'aggrégation pour cash balance
cc_balance_agg = agg_fichiers(credit_card_balance, prefix="CC")
cc_balance_agg.info()

Début agg numériques
Fin agg numériques
Début nunique cat
Fin nunique cat
Début dummies + groupby cat
Traitement 1/1 : NAME_CONTRACT_STATUS
Fin catégoriel
Fusion finale
Agrégation terminée
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103558 entries, 0 to 103557
Data columns (total 97 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   SK_ID_CURR                             103558 non-null  int64
 1   CC_MONTHS_BALANCE_mean                 103558 non-null  float64
 2   CC_MONTHS_BALANCE_max                  103558 non-null  int64
 3   CC_MONTHS_BALANCE_min                  103558 non-null  int64
 4   CC_MONTHS_BALANCE_sum                  103558 non-null  int64
 5   CC_AMT_BALANCE_mean                    103558 non-null  float64
 6   CC_AMT_BALANCE_max                     103558 non-null  float64
 7   CC_AMT_BALANCE_min                     103558 non-null  float64
 8   CC_AMT_BALANCE_sum                     103558 non-null  float64
 9   CC_AMT_CREDIT_LIMIT_ACTUAL_mean        103558 non-null  float64
 10  CC_AMT_CREDIT_LIMIT_ACTUAL_max         103558 non-null  int64
 11  CC_AMT_CREDIT_LIMIT_ACTUAL_min         103558 non-null  int64
 12  CC_AMT_CREDIT_LIMIT_ACTUAL_sum         103558 non-null  int64
 13  CC_AMT_DRAWINGS_ATM_CURRENT_mean       72194 non-null   float64
 14  CC_AMT_DRAWINGS_ATM_CURRENT_max        72194 non-null   float64
 15  CC_AMT_DRAWINGS_ATM_CURRENT_min        72194 non-null   float64
 16  CC_AMT_DRAWINGS_ATM_CURRENT_sum        103558 non-null  float64
 17  CC_AMT_DRAWINGS_CURRENT_mean           103558 non-null  float64
 18  CC_AMT_DRAWINGS_CURRENT_max            103558 non-null  float64
 19  CC_AMT_DRAWINGS_CURRENT_min            103558 non-null  float64
 20  CC_AMT_DRAWINGS_CURRENT_sum            103558 non-null  float64
 21  CC_AMT_DRAWINGS_OTHER_CURRENT_mean     72194 non-null   float64
 22  CC_AMT_DRAWINGS_OTHER_CURRENT_max      72194 non-null   float64
 23  CC_AMT_DRAWINGS_OTHER_CURRENT_min      72194 non-null   float64
 24  CC_AMT_DRAWINGS_OTHER_CURRENT_sum      103558 non-null  float64
 25  CC_AMT_DRAWINGS_POS_CURRENT_mean       72194 non-null   float64
 26  CC_AMT_DRAWINGS_POS_CURRENT_max        72194 non-null   float64
 27  CC_AMT_DRAWINGS_POS_CURRENT_min        72194 non-null   float64
 28  CC_AMT_DRAWINGS_POS_CURRENT_sum        103558 non-null  float64
 29  CC_AMT_INST_MIN_REGULARITY_mean        103558 non-null  float64
 30  CC_AMT_INST_MIN_REGULARITY_max         103558 non-null  float64
 31  CC_AMT_INST_MIN_REGULARITY_min         103558 non-null  float64
 32  CC_AMT_INST_MIN_REGULARITY_sum         103558 non-null  float64
 33  CC_AMT_PAYMENT_CURRENT_mean            72120 non-null   float64
 34  CC_AMT_PAYMENT_CURRENT_max             72120 non-null   float64
 35  CC_AMT_PAYMENT_CURRENT_min             72120 non-null   float64
 36  CC_AMT_PAYMENT_CURRENT_sum             103558 non-null  float64
 37  CC_AMT_PAYMENT_TOTAL_CURRENT_mean      103558 non-null  float64
 38  CC_AMT_PAYMENT_TOTAL_CURRENT_max       103558 non-null  float64
 39  CC_AMT_PAYMENT_TOTAL_CURRENT_min       103558 non-null  float64
 40  CC_AMT_PAYMENT_TOTAL_CURRENT_sum       103558 non-null  float64
 41  CC_AMT_RECEIVABLE_PRINCIPAL_mean       103558 non-null  float64
 42  CC_AMT_RECEIVABLE_PRINCIPAL_max        103558 non-null  float64
 43  CC_AMT_RECEIVABLE_PRINCIPAL_min        103558 non-null  float64
 44  CC_AMT_RECEIVABLE_PRINCIPAL_sum        103558 non-null  float64
 45  CC_AMT_RECIVABLE_mean                  103558 non-null  float64
 46  CC_AMT_RECIVABLE_max                   103558 non-null  float64
 47  CC_AMT_RECIVABLE_min                   103558 non-null  float64
 48  CC_AMT_RECIVABLE_sum                   103558 non-null  float64
 49  CC_AMT_TOTAL_RECEIVABLE_mean           103558 non-null  float64
 50  CC_AMT_TOTAL_RECEIVABLE_max            103558 non-null  float64
 51  CC_AMT_TOTAL_RECEIVABLE_min            103558 non-null  float64
 52  CC_AMT_TOTAL_RECEIVABLE_sum            103558 non-null  float64
 53  CC_CNT_DRAWINGS_ATM_CURRENT_mean       72194 non-null   float64
 54  CC_CNT_DRAWINGS_ATM_CURRENT_max        72194 non-null   float64
 55  CC_CNT_DRAWINGS_ATM_CURRENT_min        72194 non-null   float64
 56  CC_CNT_DRAWINGS_ATM_CURRENT_sum        103558 non-null  float64
 57  CC_CNT_DRAWINGS_CURRENT_mean           103558 non-null  float64
 58  CC_CNT_DRAWINGS_CURRENT_max            103558 non-null  int64
 59  CC_CNT_DRAWINGS_CURRENT_min            103558 non-null  int64
 60  CC_CNT_DRAWINGS_CURRENT_sum            103558 non-null  int64
 61  CC_CNT_DRAWINGS_OTHER_CURRENT_mean     72194 non-null   float64
 62  CC_CNT_DRAWINGS_OTHER_CURRENT_max      72194 non-null   float64
 63  CC_CNT_DRAWINGS_OTHER_CURRENT_min      72194 non-null   float64
 64  CC_CNT_DRAWINGS_OTHER_CURRENT_sum      103558 non-null  float64
 65  CC_CNT_DRAWINGS_POS_CURRENT_mean       72194 non-null   float64
 66  CC_CNT_DRAWINGS_POS_CURRENT_max        72194 non-null   float64
 67  CC_CNT_DRAWINGS_POS_CURRENT_min        72194 non-null   float64
 68  CC_CNT_DRAWINGS_POS_CURRENT_sum        103558 non-null  float64
 69  CC_CNT_INSTALMENT_MATURE_CUM_mean      103558 non-null  float64
 70  CC_CNT_INSTALMENT_MATURE_CUM_max       103558 non-null  float64
 71  CC_CNT_INSTALMENT_MATURE_CUM_min       103558 non-null  float64
 72  CC_CNT_INSTALMENT_MATURE_CUM_sum       103558 non-null  float64
 73  CC_SK_DPD_mean                         103558 non-null  float64
 74  CC_SK_DPD_max                          103558 non-null  int64
 75  CC_SK_DPD_min                          103558 non-null  int64
 76  CC_SK_DPD_sum                          103558 non-null  int64
 77  CC_SK_DPD_DEF_mean                     103558 non-null  float64
 78  CC_SK_DPD_DEF_max                      103558 non-null  int64
 79  CC_SK_DPD_DEF_min                      103558 non-null  int64
 80  CC_SK_DPD_DEF_sum                      103558 non-null  int64
 81  CC_UTILIZATION_mean                    102445 non-null  float64
 82  CC_UTILIZATION_max                     102445 non-null  float64
 83  CC_UTILIZATION_min                     102445 non-null  float64
 84  CC_UTILIZATION_sum                     103558 non-null  float64
 85  CC_PAYMENT_RATIO_mean                  70265 non-null   float64
 86  CC_PAYMENT_RATIO_max                   70265 non-null   float64
 87  CC_PAYMENT_RATIO_min                   70265 non-null   float64
 88  CC_PAYMENT_RATIO_sum                   103558 non-null  float64
 89  CC_NAME_CONTRACT_STATUS_NUNIQUE        103558 non-null  int64
 90  CC_NAME_CONTRACT_STATUS_Active         103558 non-null  int64
 91  CC_NAME_CONTRACT_STATUS_Approved       103558 non-null  int64
 92  CC_NAME_CONTRACT_STATUS_Completed      103558 non-null  int64
 93  CC_NAME_CONTRACT_STATUS_Demand         103558 non-null  int64
 94  CC_NAME_CONTRACT_STATUS_Refused        103558 non-null  int64
 95  CC_NAME_CONTRACT_STATUS_Sent proposal  103558 non-null  int64
 96  CC_NAME_CONTRACT_STATUS_Signed         103558 non-null  int64
dtypes: float64(73), int64(24)
memory usage: 76.6 MB

In [39]:
# Fusion avec train/test
app_train_clean4 = app_train_clean3.merge(cc_balance_agg, on="SK_ID_CURR", how="left")
app_test_clean4  = app_test_clean3.merge(cc_balance_agg, on="SK_ID_CURR", how="left")

print(app_train_clean4.shape, app_test_clean4.shape)

(307511, 576) (48744, 575)

In [40]:
# Check des colonnes entre train et test
check_columns(app_train_clean4, app_test_clean4, name_ref="train_cc", name_test="test_cc")

--- Vérification colonnes : test_cc vs train_cc ---
Colonnes attendues : 576
Colonnes trouvées  : 575

❌ Colonnes manquantes dans test_cc :
   - TARGET

✔️ Aucune colonne supplémentaire

--------------------------------------------

In [41]:
# Application de la fonction d'aggrégation pour cash balance
pos_cash_balance_agg = agg_fichiers(pos_cash_balance, prefix="POS")
pos_cash_balance_agg.info()

Début agg numériques
Fin agg numériques
Début nunique cat
Fin nunique cat
Début dummies + groupby cat
Traitement 1/1 : NAME_CONTRACT_STATUS
Fin catégoriel
Fusion finale
Agrégation terminée
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 337252 entries, 0 to 337251
Data columns (total 31 columns):
 #   Column                                          Non-Null Count   Dtype
---  ------                                          --------------   -----
 0   SK_ID_CURR                                      337252 non-null  int64
 1   POS_MONTHS_BALANCE_mean                         337252 non-null  float64
 2   POS_MONTHS_BALANCE_max                          337252 non-null  int64
 3   POS_MONTHS_BALANCE_min                          337252 non-null  int64
 4   POS_MONTHS_BALANCE_sum                          337252 non-null  int64
 5   POS_CNT_INSTALMENT_mean                         337224 non-null  float64
 6   POS_CNT_INSTALMENT_max                          337224 non-null  float64
 7   POS_CNT_INSTALMENT_min                          337224 non-null  float64
 8   POS_CNT_INSTALMENT_sum                          337252 non-null  float64
 9   POS_CNT_INSTALMENT_FUTURE_mean                  337224 non-null  float64
 10  POS_CNT_INSTALMENT_FUTURE_max                   337224 non-null  float64
 11  POS_CNT_INSTALMENT_FUTURE_min                   337224 non-null  float64
 12  POS_CNT_INSTALMENT_FUTURE_sum                   337252 non-null  float64
 13  POS_SK_DPD_mean                                 337252 non-null  float64
 14  POS_SK_DPD_max                                  337252 non-null  int64
 15  POS_SK_DPD_min                                  337252 non-null  int64
 16  POS_SK_DPD_sum                                  337252 non-null  int64
 17  POS_SK_DPD_DEF_mean                             337252 non-null  float64
 18  POS_SK_DPD_DEF_max                              337252 non-null  int64
 19  POS_SK_DPD_DEF_min                              337252 non-null  int64
 20  POS_SK_DPD_DEF_sum                              337252 non-null  int64
 21  POS_NAME_CONTRACT_STATUS_NUNIQUE                337252 non-null  int64
 22  POS_NAME_CONTRACT_STATUS_Active                 337252 non-null  int64
 23  POS_NAME_CONTRACT_STATUS_Amortized debt         337252 non-null  int64
 24  POS_NAME_CONTRACT_STATUS_Approved               337252 non-null  int64
 25  POS_NAME_CONTRACT_STATUS_Canceled               337252 non-null  int64
 26  POS_NAME_CONTRACT_STATUS_Completed              337252 non-null  int64
 27  POS_NAME_CONTRACT_STATUS_Demand                 337252 non-null  int64
 28  POS_NAME_CONTRACT_STATUS_Returned to the store  337252 non-null  int64
 29  POS_NAME_CONTRACT_STATUS_Signed                 337252 non-null  int64
 30  POS_NAME_CONTRACT_STATUS_XNA                    337252 non-null  int64
dtypes: float64(11), int64(20)
memory usage: 79.8 MB

In [42]:
# Fusion avec train/test
app_train_clean5 = app_train_clean4.merge(pos_cash_balance_agg, on="SK_ID_CURR", how="left")
app_test_clean5 = app_test_clean4.merge(pos_cash_balance_agg, on="SK_ID_CURR", how="left")

print(app_train_clean5.shape, app_test_clean5.shape)

(307511, 606) (48744, 605)

In [43]:
# Check des colonnes entre train et test
check_columns(app_train_clean5, app_test_clean5, name_ref="train_pos", name_test="test_pos")

--- Vérification colonnes : test_pos vs train_pos ---
Colonnes attendues : 606
Colonnes trouvées  : 605

❌ Colonnes manquantes dans test_pos :
   - TARGET

✔️ Aucune colonne supplémentaire

--------------------------------------------

In [44]:
# Vérifier que les colonnes entre train et test sont bien identiques mis à part "TARGET"
train_cols = set(app_train_clean5.columns) - {"TARGET"}
test_cols = set(app_test_clean5.columns)

diff_train = train_cols - test_cols
diff_test = test_cols - train_cols

print("Colonnes dans train mais pas dans test :", diff_train)
print("Colonnes dans test mais pas dans train :", diff_test)

Colonnes dans train mais pas dans test : set()
Colonnes dans test mais pas dans train : set()

In [36]:
joblib.dump(app_train_clean5, "data/app_train_clean5.joblib")
joblib.dump(app_test_clean5, "data/app_test_clean5.joblib")

['data/app_test_clean5.joblib']